## 1. Carregar Informações

importa biblioteca

In [15]:
import pandas as pd

Carregando os dados

In [16]:
fifa19 = pd.read_csv('C:./Data/fifa19.csv', sep=',', skiprows=None)
fifa19.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/...,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/...,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/...,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [17]:
fifa19.head(10)

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/...,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/...,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/...,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
5,5,183277,E. Hazard,27,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,91,91,Chelsea,...,91.0,34.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0,€172.1M
6,6,177003,L. Modrić,32,https://cdn.sofifa.org/players/4/19/...,Croatia,https://cdn.sofifa.org/flags/10.png,91,91,Real Madrid,...,84.0,60.0,76.0,73.0,13.0,9.0,7.0,14.0,9.0,€137.4M
7,7,176580,L. Suárez,31,https://cdn.sofifa.org/players/4/19/...,Uruguay,https://cdn.sofifa.org/flags/60.png,91,91,FC Barcelona,...,85.0,62.0,45.0,38.0,27.0,25.0,31.0,33.0,37.0,€164M
8,8,155862,Sergio Ramos,32,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,91,Real Madrid,...,82.0,87.0,92.0,91.0,11.0,8.0,9.0,7.0,11.0,€104.6M
9,9,200389,J. Oblak,25,https://cdn.sofifa.org/players/4/19/...,Slovenia,https://cdn.sofifa.org/flags/44.png,90,93,Atlético Madrid,...,70.0,27.0,12.0,18.0,86.0,92.0,78.0,88.0,89.0,€144.5M

In [18]:
fifa19.tail(3)

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
18204,18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/...,England,https://cdn.sofifa.org/flags/14.png,47,67,Cambridge United,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/...,England,https://cdn.sofifa.org/flags/14.png,47,66,Tranmere Rovers,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/...,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

## 2. Informações sobre o dataset

In [19]:
fifa19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 89 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                18207 non-null  int64
 1   ID                        18207 non-null  int64
 2   Name                      18207 non-null  object
 3   Age                       18207 non-null  int64
 4   Photo                     18207 non-null  object
 5   Nationality               18207 non-null  object
 6   Flag                      18207 non-null  object
 7   Overall                   18207 non-null  int64
 8   Potential                 18207 non-null  int64
 9   Club                      17966 non-null  object
 10  Club Logo                 18207 non-null  object
 11  Value                     18207 non-null  object
 12  Wage                      18207 non-null  object
 13  Special                   18207 non-null  int64
 14  Preferred Foot            18159 non-null  object
 15  International Reputation  18159 non-null  float64
 16  Weak Foot                 18159 non-null  float64
 17  Skill Moves               18159 non-null  float64
 18  Work Rate                 18159 non-null  object
 19  Body Type                 18159 non-null  object
 20  Real Face                 18159 non-null  object
 21  Position                  18147 non-null  object
 22  Jersey Number             18147 non-null  float64
 23  Joined                    16654 non-null  object
 24  Loaned From               1264 non-null   object
 25  Contract Valid Until      17918 non-null  object
 26  Height                    18159 non-null  object
 27  Weight                    18159 non-null  object
 28  LS                        16122 non-null  object
 29  ST                        16122 non-null  object
 30  RS                        16122 non-null  object
 31  LW                        16122 non-null  object
 32  LF                        16122 non-null  object
 33  CF                        16122 non-null  object
 34  RF                        16122 non-null  object
 35  RW                        16122 non-null  object
 36  LAM                       16122 non-null  object
 37  CAM                       16122 non-null  object
 38  RAM                       16122 non-null  object
 39  LM                        16122 non-null  object
 40  LCM                       16122 non-null  object
 41  CM                        16122 non-null  object
 42  RCM                       16122 non-null  object
 43  RM                        16122 non-null  object
 44  LWB                       16122 non-null  object
 45  LDM                       16122 non-null  object
 46  CDM                       16122 non-null  object
 47  RDM                       16122 non-null  object
 48  RWB                       16122 non-null  object
 49  LB                        16122 non-null  object
 50  LCB                       16122 non-null  object
 51  CB                        16122 non-null  object
 52  RCB                       16122 non-null  object
 53  RB                        16122 non-null  object
 54  Crossing                  18159 non-null  float64
 55  Finishing                 18159 non-null  float64
 56  HeadingAccuracy           18159 non-null  float64
 57  ShortPassing              18159 non-null  float64
 58  Volleys                   18159 non-null  float64
 59  Dribbling                 18159 non-null  float64
 60  Curve                     18159 non-null  float64
 61  FKAccuracy                18159 non-null  float64
 62  LongPassing               18159 non-null  float64
 63  BallControl               18159 non-null  float64
 64  Acceleration              18159 non-null  float64
 65  SprintSpeed               18159 non-null  float64
 66  Agility                   18159 non-null  float64
 67  Reactions                 18159 non-null  float64
 68  Balance                   18159 non-null  float64
 69  ShotPower                 18159 non-null  float64
 70  Jumping                   18159 non-null  float64
 71  Stamina                   18159 non-null  float64
 72  Strength                  18159 non-null  float64
 73  LongShots                 18159 non-null  float64
 74  Aggression                18159 non-null  float64
 75  Interceptions             18159 non-null  float64
 76  Positioning               18159 non-null  float64
 77  Vision                    18159 non-null  float64
 78  Penalties                 18159 non-null  float64
 79  Composure                 18159 non-null  float64
 80  Marking                   18159 non-null  float64
 81  StandingTackle            18159 non-null  float64
 82  SlidingTackle             18159 non-null  float64
 83  GKDiving                  18159 non-null  float64
 84  GKHandling                18159 non-null  float64
 85  GKKicking                 18159 non-null  float64
 86  GKPositioning             18159 non-null  float64
 87  GKReflexes                18159 non-null  float64
 88  Release Clause            16643 non-null  object
dtypes: float64(38), int64(6), object(45)
memory usage: 12.4+ MB

In [20]:
fifa19.shape

(18207, 89)

In [21]:
fifa19.shape[0]

18207

In [22]:
fifa19.shape[1]

89

In [23]:
print("Temos %0.f linhas e %0.f colunas"%(fifa19.shape[0], fifa19.shape[1]))

Temos 18207 linhas e 89 colunas

In [24]:
fifa19.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')

In [25]:
fifa19.index

RangeIndex(start=0, stop=18207, step=1)

Se quiser estabelecer uma coluna como índice é só usar set_index, por exemplo:
- df.set_index('nome da coluna') # para uma coluna
- df.set_index(['nome da coluna 1', 'nome da coluna 2', ..., 'nome da coluna n'] # para varias colunas
- df.set_index([pd.index)[1,2,3,4...],'nome do indice') # pra criar um indice novo do zero

In [26]:
print(fifa19.head())
print(fifa19.tail())

   Unnamed: 0      ID               Name  Age  \
0           0  158023           L. Messi   31
1           1   20801  Cristiano Ronaldo   33
2           2  190871          Neymar Jr   26
3           3  193080             De Gea   27
4           4  192985       K. De Bruyne   27

                                     Photo Nationality  \
0  https://cdn.sofifa.org/players/4/19/...   Argentina
1  https://cdn.sofifa.org/players/4/19/...    Portugal
2  https://cdn.sofifa.org/players/4/19/...      Brazil
3  https://cdn.sofifa.org/players/4/19/...       Spain
4  https://cdn.sofifa.org/players/4/19/...     Belgium

                                  Flag  Overall  Potential  \
0  https://cdn.sofifa.org/flags/52.png       94         94
1  https://cdn.sofifa.org/flags/38.png       94         94
2  https://cdn.sofifa.org/flags/54.png       92         93
3  https://cdn.sofifa.org/flags/45.png       91         93
4   https://cdn.sofifa.org/flags/7.png       91         92

                  Club  ... Composure Marking StandingTackle  SlidingTackle  \
0         FC Barcelona  ...      96.0    33.0           28.0           26.0
1             Juventus  ...      95.0    28.0           31.0           23.0
2  Paris Saint-Germain  ...      94.0    27.0           24.0           33.0
3    Manchester United  ...      68.0    15.0           21.0           13.0
4      Manchester City  ...      88.0    68.0           58.0           51.0

  GKDiving  GKHandling  GKKicking  GKPositioning GKReflexes Release Clause
0      6.0        11.0       15.0           14.0        8.0        €226.5M
1      7.0        11.0       15.0           14.0       11.0        €127.1M
2      9.0         9.0       15.0           15.0       11.0        €228.1M
3     90.0        85.0       87.0           88.0       94.0        €138.6M
4     15.0        13.0        5.0           10.0       13.0        €196.4M

[5 rows x 89 columns]
       Unnamed: 0      ID                Name  Age  \
18202       18202  238813        J. Lundstram   19
18203       18203  243165  N. Christoffersson   19
18204       18204  241638           B. Worman   16
18205       18205  246268      D. Walker-Rice   17
18206       18206  246269           G. Nugent   16

                                         Photo Nationality  \
18202  https://cdn.sofifa.org/players/4/19/...     England
18203  https://cdn.sofifa.org/players/4/19/...      Sweden
18204  https://cdn.sofifa.org/players/4/19/...     England
18205  https://cdn.sofifa.org/players/4/19/...     England
18206  https://cdn.sofifa.org/players/4/19/...     England

                                      Flag  Overall  Potential  \
18202  https://cdn.sofifa.org/flags/14.png       47         65
18203  https://cdn.sofifa.org/flags/46.png       47         63
18204  https://cdn.sofifa.org/flags/14.png       47         67
18205  https://cdn.sofifa.org/flags/14.png       47         66
18206  https://cdn.sofifa.org/flags/14.png       46         66

                   Club  ... Composure Marking StandingTackle  SlidingTackle  \
18202   Crewe Alexandra  ...      45.0    40.0           48.0           47.0
18203    Trelleborgs FF  ...      42.0    22.0           15.0           19.0
18204  Cambridge United  ...      41.0    32.0           13.0           11.0
18205   Tranmere Rovers  ...      46.0    20.0           25.0           27.0
18206   Tranmere Rovers  ...      43.0    40.0           43.0           50.0

      GKDiving  GKHandling  GKKicking  GKPositioning GKReflexes Release Clause
18202     10.0        13.0        7.0            8.0        9.0          €143K
18203     10.0         9.0        9.0            5.0       12.0          €113K
18204      6.0         5.0       10.0            6.0       13.0          €165K
18205     14.0         6.0       14.0            8.0        9.0          €143K
18206     10.0        15.0        9.0           12.0        9.0          €165K

[5 rows x 89 columns]

In [27]:
print(fifa19.head(50))

    Unnamed: 0      ID               Name  Age  \
0            0  158023           L. Messi   31
1            1   20801  Cristiano Ronaldo   33
2            2  190871          Neymar Jr   26
3            3  193080             De Gea   27
4            4  192985       K. De Bruyne   27
5            5  183277          E. Hazard   27
6            6  177003          L. Modrić   32
7            7  176580          L. Suárez   31
8            8  155862       Sergio Ramos   32
9            9  200389           J. Oblak   25
10          10  188545     R. Lewandowski   29
11          11  182521           T. Kroos   28
12          12  182493           D. Godín   32
13          13  168542        David Silva   32
14          14  215914           N. Kanté   27
15          15  211110          P. Dybala   24
16          16  202126            H. Kane   24
17          17  194765       A. Griezmann   27
18          18  192448      M. ter Stegen   26
19          19  192119        T. Courtois   26
20          20  189511    Sergio Busquets   29
21          21  179813          E. Cavani   31
22          22  167495           M. Neuer   32
23          23  153079          S. Agüero   30
24          24  138956       G. Chiellini   33
25          25  231747          K. Mbappé   19
26          26  209331           M. Salah   26
27          27  200145           Casemiro   26
28          28  198710       J. Rodríguez   26
29          29  198219         L. Insigne   27
30          30  197781               Isco   26
31          31  190460         C. Eriksen   26
32          32  189242           Coutinho   26
33          33  188567      P. Aubameyang   29
34          34  178603         M. Hummels   29
35          35  176676            Marcelo   30
36          36  173731            G. Bale   28
37          37  167948          H. Lloris   31
38          38  167664         G. Higuaín   30
39          39  164240       Thiago Silva   33
40          40  162835      S. Handanovič   33
41          41    1179          G. Buffon   40
42          42  205600          S. Umtiti   24
43          43  201399          M. Icardi   25
44          44  201024       K. Koulibaly   27
45          45  195864           P. Pogba   25
46          46  193041           K. Navas   31
47          47  192505          R. Lukaku   25
48          48  192387        C. Immobile   28
49          49  189332         Jordi Alba   29

                                      Photo Nationality  \
0   https://cdn.sofifa.org/players/4/19/...   Argentina
1   https://cdn.sofifa.org/players/4/19/...    Portugal
2   https://cdn.sofifa.org/players/4/19/...      Brazil
3   https://cdn.sofifa.org/players/4/19/...       Spain
4   https://cdn.sofifa.org/players/4/19/...     Belgium
5   https://cdn.sofifa.org/players/4/19/...     Belgium
6   https://cdn.sofifa.org/players/4/19/...     Croatia
7   https://cdn.sofifa.org/players/4/19/...     Uruguay
8   https://cdn.sofifa.org/players/4/19/...       Spain
9   https://cdn.sofifa.org/players/4/19/...    Slovenia
10  https://cdn.sofifa.org/players/4/19/...      Poland
11  https://cdn.sofifa.org/players/4/19/...     Germany
12  https://cdn.sofifa.org/players/4/19/...     Uruguay
13  https://cdn.sofifa.org/players/4/19/...       Spain
14  https://cdn.sofifa.org/players/4/19/...      France
15  https://cdn.sofifa.org/players/4/19/...   Argentina
16  https://cdn.sofifa.org/players/4/19/...     England
17  https://cdn.sofifa.org/players/4/19/...      France
18  https://cdn.sofifa.org/players/4/19/...     Germany
19  https://cdn.sofifa.org/players/4/19/...     Belgium
20  https://cdn.sofifa.org/players/4/19/...       Spain
21  https://cdn.sofifa.org/players/4/19/...     Uruguay
22  https://cdn.sofifa.org/players/4/19/...     Germany
23  https://cdn.sofifa.org/players/4/19/...   Argentina
24  https://cdn.sofifa.org/players/4/19/...       Italy
25  https://cdn.sofifa.org/players/4/19/...      France
26  https://cdn.sofifa.org/players/4/19/...       Egypt
27  https://cdn.sofifa.org/players/4/19/...      Brazil
28  https://cdn.sofifa.org/players/4/19/...    Colombia
29  https://cdn.sofifa.org/players/4/19/...       Italy
30  https://cdn.sofifa.org/players/4/19/...       Spain
31  https://cdn.sofifa.org/players/4/19/...     Denmark
32  https://cdn.sofifa.org/players/4/19/...      Brazil
33  https://cdn.sofifa.org/players/4/19/...       Gabon
34  https://cdn.sofifa.org/players/4/19/...     Germany
35  https://cdn.sofifa.org/players/4/19/...      Brazil
36  https://cdn.sofifa.org/players/4/19/...       Wales
37  https://cdn.sofifa.org/players/4/19/...      France
38  https://cdn.sofifa.org/players/4/19/...   Argentina
39  https://cdn.sofifa.org/players/4/19/...      Brazil
40  https://cdn.sofifa.org/players/4/19/...    Slovenia
41  https://cdn.sofifa.org/players/4/19/...       Italy
42  https://cdn.sofifa.org/players/4/19/...      France
43  https://cdn.sofifa.org/players/4/19/...   Argentina
44  https://cdn.sofifa.org/players/4/19/...     Senegal
45  https://cdn.sofifa.org/players/4/19/...      France
46  https://cdn.sofifa.org/players/4/19/...  Costa Rica
47  https://cdn.sofifa.org/players/4/19/...     Belgium
48  https://cdn.sofifa.org/players/4/19/...       Italy
49  https://cdn.sofifa.org/players/4/19/...       Spain

                                    Flag  Overall  Potential  \
0    https://cdn.sofifa.org/flags/52.png       94         94
1    https://cdn.sofifa.org/flags/38.png       94         94
2    https://cdn.sofifa.org/flags/54.png       92         93
3    https://cdn.sofifa.org/flags/45.png       91         93
4     https://cdn.sofifa.org/flags/7.png       91         92
5     https://cdn.sofifa.org/flags/7.png       91         91
6    https://cdn.sofifa.org/flags/10.png       91         91
7    https://cdn.sofifa.org/flags/60.png       91         91
8    https://cdn.sofifa.org/flags/45.png       91         91
9    https://cdn.sofifa.org/flags/44.png       90         93
10   https://cdn.sofifa.org/flags/37.png       90         90
11   https://cdn.sofifa.org/flags/21.png       90         90
12   https://cdn.sofifa.org/flags/60.png       90         90
13   https://cdn.sofifa.org/flags/45.png       90         90
14   https://cdn.sofifa.org/flags/18.png       89         90
15   https://cdn.sofifa.org/flags/52.png       89         94
16   https://cdn.sofifa.org/flags/14.png       89         91
17   https://cdn.sofifa.org/flags/18.png       89         90
18   https://cdn.sofifa.org/flags/21.png       89         92
19    https://cdn.sofifa.org/flags/7.png       89         90
20   https://cdn.sofifa.org/flags/45.png       89         89
21   https://cdn.sofifa.org/flags/60.png       89         89
22   https://cdn.sofifa.org/flags/21.png       89         89
23   https://cdn.sofifa.org/flags/52.png       89         89
24   https://cdn.sofifa.org/flags/27.png       89         89
25   https://cdn.sofifa.org/flags/18.png       88         95
26  https://cdn.sofifa.org/flags/111.png       88         89
27   https://cdn.sofifa.org/flags/54.png       88         90
28   https://cdn.sofifa.org/flags/56.png       88         89
29   https://cdn.sofifa.org/flags/27.png       88         88
30   https://cdn.sofifa.org/flags/45.png       88         91
31   https://cdn.sofifa.org/flags/13.png       88         91
32   https://cdn.sofifa.org/flags/54.png       88         89
33  https://cdn.sofifa.org/flags/115.png       88         88
34   https://cdn.sofifa.org/flags/21.png       88         88
35   https://cdn.sofifa.org/flags/54.png       88         88
36   https://cdn.sofifa.org/flags/50.png       88         88
37   https://cdn.sofifa.org/flags/18.png       88         88
38   https://cdn.sofifa.org/flags/52.png       88         88
39   https://cdn.sofifa.org/flags/54.png       88         88
40   https://cdn.sofifa.org/flags/44.png       88         88
41   https://cdn.sofifa.org/flags/27.png       88         88
42   https://cdn.sofifa.org/flags/18.png       87         92
43   https://cdn.sofifa.org/flags/52.png       87         90
44  https://cdn.sofifa.org/flags/136.png       87         90
45   https://cdn.sofifa.org/flags/18.png       87         91
46   https://cdn.sofifa.org/flags/72.png       87         87
47    https://cdn.sofifa.org/flags/7.png       87         89
48   https://cdn.sofifa.org/flags/27.png       87         87
49   https://cdn.sofifa.org/flags/45.png       87         87

                   Club  ... Composure Marking StandingTackle  SlidingTackle  \
0          FC Barcelona  ...      96.0    33.0           28.0           26.0
1              Juventus  ...      95.0    28.0           31.0           23.0
2   Paris Saint-Germain  ...      94.0    27.0           24.0           33.0
3     Manchester United  ...      68.0    15.0           21.0           13.0
4       Manchester City  ...      88.0    68.0           58.0           51.0
5               Chelsea  ...      91.0    34.0           27.0           22.0
6           Real Madrid  ...      84.0    60.0           76.0           73.0
7          FC Barcelona  ...      85.0    62.0           45.0           38.0
8           Real Madrid  ...      82.0    87.0           92.0           91.0
9       Atlético Madrid  ...      70.0    27.0           12.0           18.0
10    FC Bayern München  ...      86.0    34.0           42.0           19.0
11          Real Madrid  ...      85.0    72.0           79.0           69.0
12      Atlético Madrid  ...      82.0    90.0           89.0           89.0
13      Manchester City  ...      93.0    59.0           53.0           29.0
14              Chelsea  ...      85.0    90.0           91.0           85.0
15             Juventus  ...      84.0    23.0           20.0           20.0
16    Tottenham Hotspur  ...      89.0    56.0           36.0           38.0
17      Atlético Madrid  ...      87.0    59.0           47.0           48.0
18         FC Barcelona  ...      69.0    25.0           13.0           10.0
19          Real Madrid  ...      66.0    20.0           18.0           16.0
20         FC Barcelona  ...      90.0    90.0           86.0           80.0
21  Paris Saint-Germain  ...      82.0    52.0           45.0           39.0
22    FC Bayern München  ...      70.0    17.0           10.0           11.0
23      Manchester City  ...      90.0    30.0           20.0           12.0
24             Juventus  ...      84.0    93.0           93.0           90.0
25  Paris Saint-Germain  ...      86.0    34.0           34.0           32.0
26            Liverpool  ...      91.0    38.0           43.0           41.0
27          Real Madrid  ...      84.0    88.0           90.0           87.0
28    FC Bayern München  ...      87.0    52.0           41.0           44.0
29               Napoli  ...      83.0    51.0           24.0           22.0
30          Real Madrid  ...      86.0    60.0           64.0           51.0
31    Tottenham Hotspur  ...      88.0    59.0           57.0           22.0
32         FC Barcelona  ...      85.0    55.0           54.0           47.0
33              Arsenal  ...      86.0    27.0           25.0           36.0
34    FC Bayern München  ...      91.0    88.0           90.0           88.0
35          Real Madrid  ...      86.0    71.0           85.0           86.0
36          Real Madrid  ...      86.0    54.0           55.0           52.0
37    Tottenham Hotspur  ...      65.0    29.0           10.0           18.0
38                Milan  ...      86.0    35.0           22.0           18.0
39  Paris Saint-Germain  ...      81.0    88.0           89.0           85.0
40                Inter  ...      69.0    25.0           10.0           13.0
41  Paris Saint-Germain  ...      70.0    13.0           11.0           11.0
42         FC Barcelona  ...      82.0    90.0           89.0           86.0
43                Inter  ...      85.0    45.0           24.0           20.0
44               Napoli  ...      78.0    91.0           88.0           86.0
45    Manchester United  ...      87.0    66.0           70.0           68.0
46          Real Madrid  ...      67.0    28.0           14.0           14.0
47    Manchester United  ...      83.0    30.0           30.0           30.0
48                Lazio  ...      81.0    34.0           33.0           32.0
49         FC Barcelona  ...      79.0    72.0           84.0           85.0

   GKDiving  GKHandling  GKKicking  GKPositioning GKReflexes Release Clause
0       6.0        11.0       15.0           14.0        8.0        €226.5M
1       7.0        11.0       15.0           14.0       11.0        €127.1M
2       9.0         9.0       15.0           15.0       11.0        €228.1M
3      90.0        85.0       87.0           88.0       94.0        €138.6M
4      15.0        13.0        5.0           10.0       13.0        €196.4M
5      11.0        12.0        6.0            8.0        8.0        €172.1M
6      13.0         9.0        7.0           14.0        9.0        €137.4M
7      27.0        25.0       31.0           33.0       37.0          €164M
8      11.0         8.0        9.0            7.0       11.0        €104.6M
9      86.0        92.0       78.0           88.0       89.0        €144.5M
10     15.0         6.0       12.0            8.0       10.0        €127.1M
11     10.0        11.0       13.0            7.0       10.0        €156.8M
12      6.0         8.0       15.0            5.0       15.0         €90.2M
13      6.0        15.0        7.0            6.0       12.0          €111M
14     15.0        12.0       10.0            7.0       10.0        €121.3M
15      5.0         4.0        4.0            5.0        8.0        €153.5M
16      8.0        10.0       11.0           14.0       11.0        €160.7M
17     14.0         8.0       14.0           13.0       14.0        €165.8M
18     87.0        85.0       88.0           85.0       90.0        €123.3M
19     85.0        91.0       72.0           86.0       88.0        €113.7M
20      5.0         8.0       13.0            9.0       13.0        €105.6M
21     12.0         5.0       13.0           13.0       10.0          €111M
22     90.0        86.0       91.0           87.0       87.0         €62.7M
23     13.0        15.0        6.0           11.0       14.0        €119.3M
24      3.0         3.0        2.0            4.0        3.0         €44.6M
25     13.0         5.0        7.0           11.0        6.0        €166.1M
26     14.0        14.0        9.0           11.0       14.0        €137.3M
27     13.0        14.0       16.0           12.0       12.0        €126.4M
28     15.0        15.0       15.0            5.0       14.0            NaN
29      8.0         4.0       14.0            9.0       10.0        €105.4M
30     10.0         8.0       12.0           15.0        6.0        €156.2M
31      9.0        14.0        7.0            7.0        6.0        €141.5M
32     12.0         7.0        9.0           14.0        6.0        €147.7M
33      6.0         9.0       15.0            9.0        9.0        €112.1M
34     15.0         6.0       10.0            5.0        6.0         €75.9M
35     12.0         5.0        5.0            5.0        9.0         €88.2M
36     15.0        15.0       11.0            5.0        6.0          €123M
37     88.0        84.0       68.0           83.0       92.0         €66.6M
38      5.0        12.0        7.0            5.0       10.0            NaN
39      9.0        12.0        5.0            9.0       10.0         €44.4M
40     87.0        86.0       69.0           89.0       89.0           €51M
41     88.0        87.0       74.0           90.0       83.0          €7.4M
42     15.0        10.0       14.0           12.0       15.0        €121.1M
43     13.0         9.0        5.0            7.0        9.0        €114.5M
44      7.0        11.0        7.0           13.0        5.0         €90.5M
45      5.0         6.0        2.0            4.0        3.0        €123.2M
46     90.0        81.0       75.0           82.0       90.0         €62.5M
47      8.0        15.0       14.0            7.0       10.0        €120.3M
48      6.0         8.0       15.0           12.0        6.0         €88.4M
49     13.0        15.0       13.0            6.0       13.0         €77.9M

[50 rows x 89 columns]

In [28]:
def low_values_red(value):
    color = 'red' if value < 92 else 'black'
    return 'color: %s'%color # 'color: red' ou 'color: black'

fifa19[['Overall','Potential']].head(10).style.applymap(low_values_red)

In [29]:
fifa19.head(10).style.applymap(low_values_red, subset=['Overall', 'Potential'])

In [30]:
def highlight_max(s):
    is_max = s == s.max() # checa esse booleano s == s.max(), e depois guarda em is_max
    return ['background-color: yellow' if v else '' for v in is_max] 

fifa19.head(10).style.apply(highlight_max, subset=['Age','Overall', 'Potential'])

In [31]:
fifa19[['Overall','Potential']].head(10).style.\
applymap(low_values_red).\
apply(highlight_max)

Mais sobre formatação em: https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html

## 3. Filtros e Seleções

In [32]:
fifa19.head(5)

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/...,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/...,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/...,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [33]:
fifa19.loc[1]

Unnamed: 0                                              1
ID                                                  20801
Name                                    Cristiano Ronaldo
Age                                                    33
Photo             https://cdn.sofifa.org/players/4/19/...
                                   ...
GKHandling                                           11.0
GKKicking                                            15.0
GKPositioning                                        14.0
GKReflexes                                           11.0
Release Clause                                    €127.1M
Name: 1, Length: 89, dtype: object

In [34]:
fifa19.loc[0:5]

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/...,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/...,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/...,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
5,5,183277,E. Hazard,27,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,91,91,Chelsea,...,91.0,34.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0,€172.1M

In [35]:
fifa19[0:5]

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/...,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/...,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/...,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [36]:
fifa19.loc[0:5, 'Age']

0    31
1    33
2    26
3    27
4    27
5    27
Name: Age, dtype: int64

In [37]:
fifa19.iloc[0:5, 1:4]

       ID               Name  Age
0  158023           L. Messi   31
1   20801  Cristiano Ronaldo   33
2  190871          Neymar Jr   26
3  193080             De Gea   27
4  192985       K. De Bruyne   27

In [38]:
fifa19[0:10]

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/...,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/...,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/...,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
5,5,183277,E. Hazard,27,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,91,91,Chelsea,...,91.0,34.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0,€172.1M
6,6,177003,L. Modrić,32,https://cdn.sofifa.org/players/4/19/...,Croatia,https://cdn.sofifa.org/flags/10.png,91,91,Real Madrid,...,84.0,60.0,76.0,73.0,13.0,9.0,7.0,14.0,9.0,€137.4M
7,7,176580,L. Suárez,31,https://cdn.sofifa.org/players/4/19/...,Uruguay,https://cdn.sofifa.org/flags/60.png,91,91,FC Barcelona,...,85.0,62.0,45.0,38.0,27.0,25.0,31.0,33.0,37.0,€164M
8,8,155862,Sergio Ramos,32,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,91,Real Madrid,...,82.0,87.0,92.0,91.0,11.0,8.0,9.0,7.0,11.0,€104.6M
9,9,200389,J. Oblak,25,https://cdn.sofifa.org/players/4/19/...,Slovenia,https://cdn.sofifa.org/flags/44.png,90,93,Atlético Madrid,...,70.0,27.0,12.0,18.0,86.0,92.0,78.0,88.0,89.0,€144.5M

In [39]:
fifa19.loc[(fifa19['Age'] > 30) & (fifa19['Overall']>=90)]

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/...,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/...,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
6,6,177003,L. Modrić,32,https://cdn.sofifa.org/players/4/19/...,Croatia,https://cdn.sofifa.org/flags/10.png,91,91,Real Madrid,...,84.0,60.0,76.0,73.0,13.0,9.0,7.0,14.0,9.0,€137.4M
7,7,176580,L. Suárez,31,https://cdn.sofifa.org/players/4/19/...,Uruguay,https://cdn.sofifa.org/flags/60.png,91,91,FC Barcelona,...,85.0,62.0,45.0,38.0,27.0,25.0,31.0,33.0,37.0,€164M
8,8,155862,Sergio Ramos,32,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,91,Real Madrid,...,82.0,87.0,92.0,91.0,11.0,8.0,9.0,7.0,11.0,€104.6M
12,12,182493,D. Godín,32,https://cdn.sofifa.org/players/4/19/...,Uruguay,https://cdn.sofifa.org/flags/60.png,90,90,Atlético Madrid,...,82.0,90.0,89.0,89.0,6.0,8.0,15.0,5.0,15.0,€90.2M
13,13,168542,David Silva,32,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,90,90,Manchester City,...,93.0,59.0,53.0,29.0,6.0,15.0,7.0,6.0,12.0,€111M

In [40]:
tiozoes_do_fifa = fifa19.query("Age > 30")
tiozoes_do_fifa.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/...,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/...,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
6,6,177003,L. Modrić,32,https://cdn.sofifa.org/players/4/19/...,Croatia,https://cdn.sofifa.org/flags/10.png,91,91,Real Madrid,...,84.0,60.0,76.0,73.0,13.0,9.0,7.0,14.0,9.0,€137.4M
7,7,176580,L. Suárez,31,https://cdn.sofifa.org/players/4/19/...,Uruguay,https://cdn.sofifa.org/flags/60.png,91,91,FC Barcelona,...,85.0,62.0,45.0,38.0,27.0,25.0,31.0,33.0,37.0,€164M
8,8,155862,Sergio Ramos,32,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,91,Real Madrid,...,82.0,87.0,92.0,91.0,11.0,8.0,9.0,7.0,11.0,€104.6M

In [41]:
fifa19[fifa19['Age']>30]

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/...,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/...,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
6,6,177003,L. Modrić,32,https://cdn.sofifa.org/players/4/19/...,Croatia,https://cdn.sofifa.org/flags/10.png,91,91,Real Madrid,...,84.0,60.0,76.0,73.0,13.0,9.0,7.0,14.0,9.0,€137.4M
7,7,176580,L. Suárez,31,https://cdn.sofifa.org/players/4/19/...,Uruguay,https://cdn.sofifa.org/flags/60.png,91,91,FC Barcelona,...,85.0,62.0,45.0,38.0,27.0,25.0,31.0,33.0,37.0,€164M
8,8,155862,Sergio Ramos,32,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,91,Real Madrid,...,82.0,87.0,92.0,91.0,11.0,8.0,9.0,7.0,11.0,€104.6M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17842,17842,182461,Zhou Ting,39,https://cdn.sofifa.org/players/4/19/...,China PR,https://cdn.sofifa.org/flags/155.png,52,52,Dalian YiFang FC,...,52.0,17.0,45.0,44.0,10.0,12.0,7.0,15.0,6.0,€22K
17866,17866,232676,N. Hatta,32,https://cdn.sofifa.org/players/4/19/...,Japan,https://cdn.sofifa.org/flags/163.png,52,52,Júbilo Iwata,...,24.0,30.0,12.0,13.0,54.0,48.0,45.0,52.0,54.0,€38K
18043,18043,237917,A. Suzuki,31,https://cdn.sofifa.org/players/4/19/...,Japan,https://cdn.sofifa.org/flags/163.png,50,50,Yokohama F. Marinos,...,31.0,13.0,10.0,14.0,49.0,48.0,54.0,52.0,54.0,€25K
18171,18171,237746,Y. Uchimura,33,https://cdn.sofifa.org/players/4/19/...,Japan,https://cdn.sofifa.org/flags/163.png,48,48,Hokkaido Consadole Sapporo,...,62.0,45.0,48.0,42.0,13.0,15.0,7.0,15.0,15.0,€25K
18183,18183,53748,K. Pilkington,44,https://cdn.sofifa.org/players/4/19/...,England,https://cdn.sofifa.org/flags/14.png,48,48,Cambridge United,...,56.0,15.0,15.0,13.0,45.0,48.0,44.0,49.0,46.0,NaN

In [42]:
fifa19[fifa19['GKDiving']==fifa19['GKHandling']]

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/...,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
24,24,138956,G. Chiellini,33,https://cdn.sofifa.org/players/4/19/...,Italy,https://cdn.sofifa.org/flags/27.png,89,89,Juventus,...,84.0,93.0,93.0,90.0,3.0,3.0,2.0,4.0,3.0,€44.6M
26,26,209331,M. Salah,26,https://cdn.sofifa.org/players/4/19/...,Egypt,https://cdn.sofifa.org/flags/111.png,88,89,Liverpool,...,91.0,38.0,43.0,41.0,14.0,14.0,9.0,11.0,14.0,€137.3M
28,28,198710,J. Rodríguez,26,https://cdn.sofifa.org/players/4/19/...,Colombia,https://cdn.sofifa.org/flags/56.png,88,89,FC Bayern München,...,87.0,52.0,41.0,44.0,15.0,15.0,15.0,5.0,14.0,NaN
36,36,173731,G. Bale,28,https://cdn.sofifa.org/players/4/19/...,Wales,https://cdn.sofifa.org/flags/50.png,88,88,Real Madrid,...,86.0,54.0,55.0,52.0,15.0,15.0,11.0,5.0,6.0,€123M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18153,18153,246270,M. Dyrmose,17,https://cdn.sofifa.org/players/4/19/...,Denmark,https://cdn.sofifa.org/flags/13.png,49,69,SønderjyskE,...,35.0,41.0,48.0,52.0,9.0,9.0,7.0,8.0,8.0,€113K
18156,18156,245533,J. Devine,18,https://cdn.sofifa.org/players/4/19/...,England,https://cdn.sofifa.org/flags/14.png,48,60,Tranmere Rovers,...,46.0,49.0,59.0,57.0,9.0,9.0,6.0,11.0,12.0,€98K
18192,18192,245571,S. Squire,18,https://cdn.sofifa.org/players/4/19/...,England,https://cdn.sofifa.org/flags/14.png,47,64,Cambridge United,...,38.0,41.0,41.0,44.0,11.0,11.0,8.0,12.0,13.0,€119K
18194,18194,245862,J. Milli,18,https://cdn.sofifa.org/players/4/19/...,Italy,https://cdn.sofifa.org/flags/27.png,47,65,Lecce,...,23.0,6.0,10.0,11.0,52.0,52.0,52.0,40.0,44.0,€109K
18199,18199,244677,M. Baldisimo,18,https://cdn.sofifa.org/players/4/19/...,Canada,https://cdn.sofifa.org/flags/70.png,47,69,Vancouver Whitecaps FC,...,40.0,48.0,49.0,49.0,7.0,7.0,9.0,14.0,15.0,€175K

In [43]:
fifa19.filter(['Age', 'ID', 'Name'])

       Age      ID                Name
0       31  158023            L. Messi
1       33   20801   Cristiano Ronaldo
2       26  190871           Neymar Jr
3       27  193080              De Gea
4       27  192985        K. De Bruyne
...    ...     ...                 ...
18202   19  238813        J. Lundstram
18203   19  243165  N. Christoffersson
18204   16  241638           B. Worman
18205   17  246268      D. Walker-Rice
18206   16  246269           G. Nugent

[18207 rows x 3 columns]

In [44]:
overall_median = fifa19['Overall'].median()
fifa19.query("Overall > @overall_median")

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/...,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/...,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/...,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8759,8759,224509,U. Rivas,22,https://cdn.sofifa.org/players/4/19/...,Mexico,https://cdn.sofifa.org/flags/83.png,67,73,Santos Laguna,...,60.0,57.0,66.0,61.0,6.0,15.0,14.0,8.0,13.0,€2M
8760,8760,214014,C. Lizarazo,27,https://cdn.sofifa.org/players/4/19/...,Colombia,https://cdn.sofifa.org/flags/56.png,67,67,América de Cali,...,63.0,54.0,40.0,28.0,12.0,11.0,13.0,8.0,7.0,€1.1M
8761,8761,104702,D. Braaten,36,https://cdn.sofifa.org/players/4/19/...,Norway,https://cdn.sofifa.org/flags/36.png,67,67,SK Brann,...,78.0,45.0,54.0,55.0,9.0,15.0,7.0,8.0,16.0,€325K
8762,8762,229631,Lazo,22,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,67,75,CD Lugo,...,45.0,45.0,33.0,31.0,11.0,7.0,9.0,11.0,6.0,NaN
8763,8763,246015,L. Mago,23,https://cdn.sofifa.org/players/4/19/...,Venezuela,https://cdn.sofifa.org/flags/61.png,67,73,NaN,...,52.0,66.0,68.0,67.0,12.0,14.0,9.0,8.0,12.0,NaN

In [45]:
df_champs = fifa19[fifa19['Nationality'].isin(['Argentina', 'Brazil', 'Germany', 'France','Italy','England'])]
df_champs.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/...,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/...,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
11,11,182521,T. Kroos,28,https://cdn.sofifa.org/players/4/19/...,Germany,https://cdn.sofifa.org/flags/21.png,90,90,Real Madrid,...,85.0,72.0,79.0,69.0,10.0,11.0,13.0,7.0,10.0,€156.8M
14,14,215914,N. Kanté,27,https://cdn.sofifa.org/players/4/19/...,France,https://cdn.sofifa.org/flags/18.png,89,90,Chelsea,...,85.0,90.0,91.0,85.0,15.0,12.0,10.0,7.0,10.0,€121.3M
15,15,211110,P. Dybala,24,https://cdn.sofifa.org/players/4/19/...,Argentina,https://cdn.sofifa.org/flags/52.png,89,94,Juventus,...,84.0,23.0,20.0,20.0,5.0,4.0,4.0,5.0,8.0,€153.5M

In [46]:
df_non_champs = fifa19[~fifa19['Nationality'].isin(['Argentina', 'Brazil', 'Germany', 'France','Italy','England'])]
df_non_champs.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/...,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
5,5,183277,E. Hazard,27,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,91,91,Chelsea,...,91.0,34.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0,€172.1M
6,6,177003,L. Modrić,32,https://cdn.sofifa.org/players/4/19/...,Croatia,https://cdn.sofifa.org/flags/10.png,91,91,Real Madrid,...,84.0,60.0,76.0,73.0,13.0,9.0,7.0,14.0,9.0,€137.4M

In [47]:
numerics = ['int16', 'int32', 'int64', 'float16','float32','float64']
fifa19_numerics = fifa19.select_dtypes(include= numerics)
fifa19_numerics.head()

,Unnamed: 0,ID,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,158023,31,94,94,2202,5.0,4.0,4.0,10.0,...,75.0,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0
1,1,20801,33,94,94,2228,5.0,4.0,5.0,7.0,...,85.0,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0
2,2,190871,26,92,93,2143,5.0,5.0,5.0,10.0,...,81.0,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0
3,3,193080,27,91,93,1471,4.0,3.0,1.0,1.0,...,40.0,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0
4,4,192985,27,91,92,2281,4.0,5.0,4.0,7.0,...,79.0,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0

In [48]:
numerics = ['int16', 'int32', 'int64', 'float16','float32','float64']
fifa19_non_numerics = fifa19.select_dtypes(exclude= numerics)
fifa19_non_numerics.head()

,Name,Photo,Nationality,Flag,Club,Club Logo,Value,Wage,Preferred Foot,Work Rate,...,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Release Clause
0,L. Messi,https://cdn.sofifa.org/players/4/19/...,Argentina,https://cdn.sofifa.org/flags/52.png,FC Barcelona,https://cdn.sofifa.org/teams/2/light...,€110.5M,€565K,Left,Medium/ Medium,...,61+2,61+2,61+2,64+2,59+2,47+2,47+2,47+2,59+2,€226.5M
1,Cristiano Ronaldo,https://cdn.sofifa.org/players/4/19/...,Portugal,https://cdn.sofifa.org/flags/38.png,Juventus,https://cdn.sofifa.org/teams/2/light...,€77M,€405K,Right,High/ Low,...,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3,€127.1M
2,Neymar Jr,https://cdn.sofifa.org/players/4/19/...,Brazil,https://cdn.sofifa.org/flags/54.png,Paris Saint-Germain,https://cdn.sofifa.org/teams/2/light...,€118.5M,€290K,Right,High/ Medium,...,60+3,60+3,60+3,65+3,60+3,47+3,47+3,47+3,60+3,€228.1M
3,De Gea,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,Manchester United,https://cdn.sofifa.org/teams/2/light...,€72M,€260K,Right,Medium/ Medium,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,€138.6M
4,K. De Bruyne,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,Manchester City,https://cdn.sofifa.org/teams/2/light...,€102M,€355K,Right,High/ High,...,77+3,77+3,77+3,77+3,73+3,66+3,66+3,66+3,73+3,€196.4M

In [49]:
fifa19.sort_values(by='Overall', ascending=False).head(10)

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/...,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/...,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/...,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
5,5,183277,E. Hazard,27,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,91,91,Chelsea,...,91.0,34.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0,€172.1M
6,6,177003,L. Modrić,32,https://cdn.sofifa.org/players/4/19/...,Croatia,https://cdn.sofifa.org/flags/10.png,91,91,Real Madrid,...,84.0,60.0,76.0,73.0,13.0,9.0,7.0,14.0,9.0,€137.4M
7,7,176580,L. Suárez,31,https://cdn.sofifa.org/players/4/19/...,Uruguay,https://cdn.sofifa.org/flags/60.png,91,91,FC Barcelona,...,85.0,62.0,45.0,38.0,27.0,25.0,31.0,33.0,37.0,€164M
8,8,155862,Sergio Ramos,32,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,91,Real Madrid,...,82.0,87.0,92.0,91.0,11.0,8.0,9.0,7.0,11.0,€104.6M
12,12,182493,D. Godín,32,https://cdn.sofifa.org/players/4/19/...,Uruguay,https://cdn.sofifa.org/flags/60.png,90,90,Atlético Madrid,...,82.0,90.0,89.0,89.0,6.0,8.0,15.0,5.0,15.0,€90.2M

In [50]:
fifa19.drop_duplicates()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/...,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/...,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/...,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/...,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/...,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/...,England,https://cdn.sofifa.org/flags/14.png,47,65,Crewe Alexandra,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/...,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,Trelleborgs FF,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/...,England,https://cdn.sofifa.org/flags/14.png,47,67,Cambridge United,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/...,England,https://cdn.sofifa.org/flags/14.png,47,66,Tranmere Rovers,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/...,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

## 4. Estatística Descritiva

In [51]:
fifa19.describe()

,Unnamed: 0,ID,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18159.000000,18159.000000,18159.000000,18147.000000,...,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000
mean,9103.000000,214298.338606,25.122206,66.238699,71.307299,1597.809908,1.113222,2.947299,2.361308,19.546096,...,48.548598,58.648274,47.281623,47.697836,45.661435,16.616223,16.391596,16.232061,16.388898,16.710887
std,5256.052511,29965.244204,4.669943,6.908930,6.136496,272.586016,0.394031,0.660456,0.756164,15.947765,...,15.704053,11.436133,19.904397,21.664004,21.289135,17.695349,16.906900,16.502864,17.034669,17.955119
min,0.000000,16.000000,16.000000,46.000000,48.000000,731.000000,1.000000,1.000000,1.000000,1.000000,...,5.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,4551.500000,200315.500000,21.000000,62.000000,67.000000,1457.000000,1.000000,3.000000,2.000000,8.000000,...,39.000000,51.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,9103.000000,221759.000000,25.000000,66.000000,71.000000,1635.000000,1.000000,3.000000,2.000000,17.000000,...,49.000000,60.000000,53.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,13654.500000,236529.500000,28.000000,71.000000,75.000000,1787.000000,1.000000,3.000000,3.000000,26.000000,...,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,18206.000000,246620.000000,45.000000,94.000000,95.000000,2346.000000,5.000000,5.000000,5.000000,99.000000,...,92.000000,96.000000,94.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [52]:
fifa19['Age'].describe(percentiles=[0.1, 0.2, 0.8, 0.99])

count    18207.000000
mean        25.122206
std          4.669943
min         16.000000
10%         19.000000
20%         21.000000
50%         25.000000
80%         29.000000
99%         36.000000
max         45.000000
Name: Age, dtype: float64

In [53]:
fifa19.agg({'Age':['min','max','skew','median'],
           'Overall':['mean','min']})

              Age    Overall
min     16.000000  46.000000
max     45.000000        NaN
skew     0.391764        NaN
median  25.000000        NaN
mean          NaN  66.238699

In [54]:
df_champs.groupby('Nationality')['Age','Overall'].mean().sort_values(by='Overall', ascending=False)

C:\Users\Pcyes_User\AppData\Local\Temp\ipykernel_2140\861255788.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df_champs.groupby('Nationality')['Age','Overall'].mean().sort_values(by='Overall', ascending=False)

                   Age    Overall
Nationality
Brazil       27.625151  71.251511
Argentina    26.205977  68.572038
Italy        25.928775  68.158120
France       24.615974  67.798687
Germany      24.338063  66.086811
England      24.030084  63.429603

In [55]:
import numpy as np
pd.pivot_table(df_champs, index='Nationality', aggfunc=np.mean)

,Acceleration,Age,Aggression,Agility,Balance,BallControl,Composure,Crossing,Curve,Dribbling,...,SlidingTackle,Special,SprintSpeed,Stamina,StandingTackle,Strength,Unnamed: 0,Vision,Volleys,Weak Foot
Nationality,,,,,,,,,,,,,,,,,,,,,
Argentina,64.625000,26.205977,56.725427,64.193376,64.376068,60.808761,60.452991,51.319444,48.883547,58.068376,...,46.340812,1639.410886,64.318376,64.162393,47.970085,65.561966,7285.958378,54.862179,44.863248,2.870726
Brazil,66.318788,27.625151,59.972121,65.201212,63.966061,63.841212,65.241212,54.699394,53.403636,60.850909,...,48.981818,1712.134220,66.701818,65.675152,51.284848,67.263030,5141.252721,58.113939,49.918788,2.945455
England,64.945081,24.030084,54.275196,63.372963,64.732649,56.073024,56.153893,47.249849,44.498491,53.234762,...,44.164756,1549.137184,64.773084,62.920941,46.067592,64.068799,11283.274368,51.326494,40.585395,2.894387
France,64.524698,24.615974,56.958288,62.819978,63.919868,59.787047,60.586169,51.739846,47.963776,56.736553,...,48.156970,1624.257112,64.714599,62.648738,50.047201,66.480790,8075.863239,54.236004,43.468716,2.915477
Germany,63.287029,24.338063,55.931381,62.354812,61.830126,56.675314,56.370711,48.337238,45.133054,53.167364,...,45.204184,1566.782972,63.690377,62.600000,47.620084,66.953975,9392.902337,51.120502,41.038494,3.133891
Italy,63.167382,25.928775,55.429185,63.065808,62.858369,59.224607,62.530758,49.763948,47.859800,55.350501,...,46.669528,1604.572650,63.341917,62.426323,48.359084,65.114449,7621.792023,51.652361,44.390558,2.846924

In [56]:
pd.pivot_table(df_champs, index=['Nationality'], values=['Age','Overall','Strength'], aggfunc=np.mean)

                   Age    Overall   Strength
Nationality
Argentina    26.205977  68.572038  65.561966
Brazil       27.625151  71.251511  67.263030
England      24.030084  63.429603  64.068799
France       24.615974  67.798687  66.480790
Germany      24.338063  66.086811  66.953975
Italy        25.928775  68.158120  65.114449

In [57]:
pd.pivot_table(df_champs, index=['Nationality','Position'], columns=['Club'],values=['Age','Overall','Strength'], aggfunc=np.mean)

                                      Age                        \
Club                  SSV Jahn Regensburg 1. FC Heidenheim 1846
Nationality Position
Argentina   CAM                       NaN                   NaN
            CB                        NaN                   NaN
            CDM                       NaN                   NaN
            CF                        NaN                   NaN
            CM                        NaN                   NaN
...                                   ...                   ...
Italy       RM                        NaN                   NaN
            RS                        NaN                   NaN
            RW                        NaN                   NaN
            RWB                       NaN                   NaN
            ST                        NaN                   NaN

                                                                      \
Club                 1. FC Kaiserslautern 1. FC Köln 1. FC Magdeburg
Nationality Position
Argentina   CAM                       NaN        NaN             NaN
            CB                        NaN        NaN             NaN
            CDM                       NaN        NaN             NaN
            CF                        NaN        NaN             NaN
            CM                        NaN        NaN             NaN
...                                   ...        ...             ...
Italy       RM                        NaN        NaN             NaN
            RS                        NaN        NaN             NaN
            RW                        NaN        NaN             NaN
            RWB                       NaN        NaN             NaN
            ST                        NaN        NaN             NaN

                                                                        \
Club                 1. FC Nürnberg 1. FC Union Berlin 1. FSV Mainz 05
Nationality Position
Argentina   CAM                 NaN                NaN             NaN
            CB                  NaN                NaN             NaN
            CDM                 NaN                NaN             NaN
            CF                  NaN                NaN             NaN
            CM                  NaN                NaN             NaN
...                             ...                ...             ...
Italy       RM                  NaN                NaN             NaN
            RS                  NaN                NaN             NaN
            RW                  NaN                NaN             NaN
            RWB                 NaN                NaN             NaN
            ST                  NaN                NaN             NaN

                                            ...       Strength  \
Club                 AC Ajaccio AC Horsens  ... Wolfsberger AC
Nationality Position                        ...
Argentina   CAM             NaN        NaN  ...            NaN
            CB              NaN        NaN  ...            NaN
            CDM             NaN        NaN  ...            NaN
            CF              NaN        NaN  ...            NaN
            CM              NaN        NaN  ...            NaN
...                         ...        ...  ...            ...
Italy       RM              NaN        NaN  ...            NaN
            RS              NaN        NaN  ...            NaN
            RW              NaN        NaN  ...            NaN
            RWB             NaN        NaN  ...            NaN
            ST              NaN        NaN  ...            NaN

                                                                \
Club                 Wolverhampton Wanderers Wycombe Wanderers
Nationality Position
Argentina   CAM                          NaN               NaN
            CB                           NaN               NaN
            CDM                          NaN               NaN
            CF                           NaN               NaN
            CM                           NaN               NaN
...                                      ...               ...
Italy       RM                           NaN               NaN
            RS                           NaN               NaN
            RW                           NaN               NaN
            RWB                          NaN               NaN
            ST                           NaN               NaN

                                                                       \
Club                 Yeni Malatyaspor Yeovil Town Yokohama F. Marinos
Nationality Position
Argentina   CAM                   NaN         NaN                 NaN
            CB                    NaN         NaN                 NaN
            CDM                   NaN         NaN                 NaN
            CF                    NaN         NaN                 NaN
            CM                    NaN         NaN                 NaN
...                               ...         ...                 ...
Italy       RM                    NaN         NaN                 NaN
            RS                    NaN         NaN                 NaN
            RW                    NaN         NaN                 NaN
            RWB                   NaN         NaN                 NaN
            ST                    NaN         NaN                 NaN

                                                                   \
Club                 Zagłębie Sosnowiec Çaykur Rizespor Örebro SK
Nationality Position
Argentina   CAM                     NaN             NaN       NaN
            CB                      NaN             NaN       NaN
            CDM                     NaN             NaN       NaN
            CF                      NaN             NaN       NaN
            CM                      NaN             NaN       NaN
...                                 ...             ...       ...
Italy       RM                      NaN             NaN       NaN
            RS                      NaN             NaN       NaN
            RW                      NaN             NaN       NaN
            RWB                     NaN             NaN       NaN
            ST                      NaN             NaN       NaN


Club                 Östersunds FK
Nationality Position
Argentina   CAM                NaN
            CB                 NaN
            CDM                NaN
            CF                 NaN
            CM                 NaN
...                            ...
Italy       RM                 NaN
            RS                 NaN
            RW                 NaN
            RWB                NaN
            ST                 NaN

[145 rows x 1737 columns]

In [58]:
df_champs.Nationality.value_counts()

England      1662
Germany      1198
Argentina     937
France        914
Brazil        827
Italy         702
Name: Nationality, dtype: int64

In [59]:
df_champs.Nationality.value_counts(normalize=True)

England      0.266346
Germany      0.191987
Argentina    0.150160
France       0.146474
Brazil       0.132532
Italy        0.112500
Name: Nationality, dtype: float64

In [60]:
df_champs.groupby('Nationality')['Position'].value_counts()

Nationality  Position
Argentina    ST          125
             CB           99
             GK           97
             LM           64
             RM           62
                        ...
Italy        RDM           4
             RWB           2
             LDM           1
             LWB           1
             RF            1
Name: Position, Length: 145, dtype: int64

## SQL no Pandas

In [61]:
import modin.pandas as pd

In [62]:
import pandasql as ps

In [63]:
query = """ 
select ID, Age, Name from fifa19 where Age > 33
"""

In [64]:
ps.sqldf(query, locals())

         ID  Age            Name
0      1179   40       G. Buffon
1        41   34         Iniesta
2    171919   35           Naldo
3    120533   35            Pepe
4     41236   36  Z. Ibrahimović
..      ...  ...             ...
888  244440   36     F. Nicastro
889   51963   44       T. Warner
890  100899   40     S. Phillips
891  182461   39       Zhou Ting
892   53748   44   K. Pilkington

[893 rows x 3 columns]